//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Адресный реестр.
    /// </summary>
    //  *** Start programmer edit section *** (АдресныйРеестр CustomAttributes)

    //  *** End programmer edit section *** (АдресныйРеестр CustomAttributes)
    [AutoAltered()]
    [Caption("Адресный реестр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АдресныйРеестрE", new string[0])]
    [View("АдресныйРеестрL", new string[0])]
    public class АдресныйРеестр : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (АдресныйРеестр CustomMembers)

        //  *** End programmer edit section *** (АдресныйРеестр CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АдресныйРеестрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресныйРеестрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресныйРеестрE", typeof(IIS.Umnyjj_dom.АдресныйРеестр));
                }
            }
            
            /// <summary>
            /// "АдресныйРеестрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресныйРеестрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресныйРеестрL", typeof(IIS.Umnyjj_dom.АдресныйРеестр));
                }
            }
        }
    }
}
