//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид услуги.
    /// </summary>
    //  *** Start programmer edit section *** (ВидУслуги CustomAttributes)

    //  *** End programmer edit section *** (ВидУслуги CustomAttributes)
    [AutoAltered()]
    [Caption("Вид услуги")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидУслугиE", new string[] {
            "Наименование as \'Наименование\'",
            "Ресурс as \'Ресурс\'",
            "Актуальность as \'Актуальность\'"})]
    [View("ВидУслугиL", new string[] {
            "Наименование as \'Наименование\'",
            "Ресурс as \'Ресурс\'",
            "Актуальность as \'Актуальность\'"})]
    public class ВидУслуги : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fРесурс;
        
        private bool fАктуальность;
        
        //  *** Start programmer edit section *** (ВидУслуги CustomMembers)

        //  *** End programmer edit section *** (ВидУслуги CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (ВидУслуги.Наименование CustomAttributes)

        //  *** End programmer edit section *** (ВидУслуги.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (ВидУслуги.Наименование Get start)

                //  *** End programmer edit section *** (ВидУслуги.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (ВидУслуги.Наименование Get end)

                //  *** End programmer edit section *** (ВидУслуги.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ВидУслуги.Наименование Set start)

                //  *** End programmer edit section *** (ВидУслуги.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (ВидУслуги.Наименование Set end)

                //  *** End programmer edit section *** (ВидУслуги.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Ресурс.
        /// </summary>
        //  *** Start programmer edit section *** (ВидУслуги.Ресурс CustomAttributes)

        //  *** End programmer edit section *** (ВидУслуги.Ресурс CustomAttributes)
        [StrLen(255)]
        public virtual string Ресурс
        {
            get
            {
                //  *** Start programmer edit section *** (ВидУслуги.Ресурс Get start)

                //  *** End programmer edit section *** (ВидУслуги.Ресурс Get start)
                string result = this.fРесурс;
                //  *** Start programmer edit section *** (ВидУслуги.Ресурс Get end)

                //  *** End programmer edit section *** (ВидУслуги.Ресурс Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ВидУслуги.Ресурс Set start)

                //  *** End programmer edit section *** (ВидУслуги.Ресурс Set start)
                this.fРесурс = value;
                //  *** Start programmer edit section *** (ВидУслуги.Ресурс Set end)

                //  *** End programmer edit section *** (ВидУслуги.Ресурс Set end)
            }
        }
        
        /// <summary>
        /// Актуальность.
        /// </summary>
        //  *** Start programmer edit section *** (ВидУслуги.Актуальность CustomAttributes)

        //  *** End programmer edit section *** (ВидУслуги.Актуальность CustomAttributes)
        public virtual bool Актуальность
        {
            get
            {
                //  *** Start programmer edit section *** (ВидУслуги.Актуальность Get start)

                //  *** End programmer edit section *** (ВидУслуги.Актуальность Get start)
                bool result = this.fАктуальность;
                //  *** Start programmer edit section *** (ВидУслуги.Актуальность Get end)

                //  *** End programmer edit section *** (ВидУслуги.Актуальность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ВидУслуги.Актуальность Set start)

                //  *** End programmer edit section *** (ВидУслуги.Актуальность Set start)
                this.fАктуальность = value;
                //  *** Start programmer edit section *** (ВидУслуги.Актуальность Set end)

                //  *** End programmer edit section *** (ВидУслуги.Актуальность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидУслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидУслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидУслугиE", typeof(IIS.Umnyjj_dom.ВидУслуги));
                }
            }
            
            /// <summary>
            /// "ВидУслугиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидУслугиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидУслугиL", typeof(IIS.Umnyjj_dom.ВидУслуги));
                }
            }
        }
    }
}
