//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дом.
    /// </summary>
    //  *** Start programmer edit section *** (Дом CustomAttributes)

    //  *** End programmer edit section *** (Дом CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДомE", new string[] {
            "Address as \'Address\'",
            "summS as \'Summ S\'",
            "УправляющаяКомпания as \'Управляющая компания\'",
            "УправляющаяКомпания.Наименование as \'Наименование\'",
            "АдресныйРеестр as \'Адресный реестр\'"})]
    [View("ДомL", new string[] {
            "Address as \'Address\'",
            "summS as \'Summ S\'",
            "УправляющаяКомпания.Наименование as \'Наименование\'"})]
    public class Дом : ICSSoft.STORMNET.DataObject
    {
        
        private string fAddress;
        
        private int fsummS;
        
        private IIS.Umnyjj_dom.УправляющаяКомпания fУправляющаяКомпания;
        
        private IIS.Umnyjj_dom.АдресныйРеестр fАдресныйРеестр;
        
        //  *** Start programmer edit section *** (Дом CustomMembers)

        //  *** End programmer edit section *** (Дом CustomMembers)

        
        /// <summary>
        /// Address.
        /// </summary>
        //  *** Start programmer edit section *** (Дом.Address CustomAttributes)

        //  *** End programmer edit section *** (Дом.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                //  *** Start programmer edit section *** (Дом.Address Get start)

                //  *** End programmer edit section *** (Дом.Address Get start)
                string result = this.fAddress;
                //  *** Start programmer edit section *** (Дом.Address Get end)

                //  *** End programmer edit section *** (Дом.Address Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Дом.Address Set start)

                //  *** End programmer edit section *** (Дом.Address Set start)
                this.fAddress = value;
                //  *** Start programmer edit section *** (Дом.Address Set end)

                //  *** End programmer edit section *** (Дом.Address Set end)
            }
        }
        
        /// <summary>
        /// summS.
        /// </summary>
        //  *** Start programmer edit section *** (Дом.summS CustomAttributes)

        //  *** End programmer edit section *** (Дом.summS CustomAttributes)
        public virtual int summS
        {
            get
            {
                //  *** Start programmer edit section *** (Дом.summS Get start)

                //  *** End programmer edit section *** (Дом.summS Get start)
                int result = this.fsummS;
                //  *** Start programmer edit section *** (Дом.summS Get end)

                //  *** End programmer edit section *** (Дом.summS Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Дом.summS Set start)

                //  *** End programmer edit section *** (Дом.summS Set start)
                this.fsummS = value;
                //  *** Start programmer edit section *** (Дом.summS Set end)

                //  *** End programmer edit section *** (Дом.summS Set end)
            }
        }
        
        /// <summary>
        /// Дом.
        /// </summary>
        //  *** Start programmer edit section *** (Дом.УправляющаяКомпания CustomAttributes)

        //  *** End programmer edit section *** (Дом.УправляющаяКомпания CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.УправляющаяКомпания УправляющаяКомпания
        {
            get
            {
                //  *** Start programmer edit section *** (Дом.УправляющаяКомпания Get start)

                //  *** End programmer edit section *** (Дом.УправляющаяКомпания Get start)
                IIS.Umnyjj_dom.УправляющаяКомпания result = this.fУправляющаяКомпания;
                //  *** Start programmer edit section *** (Дом.УправляющаяКомпания Get end)

                //  *** End programmer edit section *** (Дом.УправляющаяКомпания Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Дом.УправляющаяКомпания Set start)

                //  *** End programmer edit section *** (Дом.УправляющаяКомпания Set start)
                this.fУправляющаяКомпания = value;
                //  *** Start programmer edit section *** (Дом.УправляющаяКомпания Set end)

                //  *** End programmer edit section *** (Дом.УправляющаяКомпания Set end)
            }
        }
        
        /// <summary>
        /// Дом.
        /// </summary>
        //  *** Start programmer edit section *** (Дом.АдресныйРеестр CustomAttributes)

        //  *** End programmer edit section *** (Дом.АдресныйРеестр CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.АдресныйРеестр АдресныйРеестр
        {
            get
            {
                //  *** Start programmer edit section *** (Дом.АдресныйРеестр Get start)

                //  *** End programmer edit section *** (Дом.АдресныйРеестр Get start)
                IIS.Umnyjj_dom.АдресныйРеестр result = this.fАдресныйРеестр;
                //  *** Start programmer edit section *** (Дом.АдресныйРеестр Get end)

                //  *** End programmer edit section *** (Дом.АдресныйРеестр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Дом.АдресныйРеестр Set start)

                //  *** End programmer edit section *** (Дом.АдресныйРеестр Set start)
                this.fАдресныйРеестр = value;
                //  *** Start programmer edit section *** (Дом.АдресныйРеестр Set end)

                //  *** End programmer edit section *** (Дом.АдресныйРеестр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДомE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомE", typeof(IIS.Umnyjj_dom.Дом));
                }
            }
            
            /// <summary>
            /// "ДомL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомL", typeof(IIS.Umnyjj_dom.Дом));
                }
            }
        }
    }
}
