//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дом поставщик.
    /// </summary>
    //  *** Start programmer edit section *** (ДомПоставщик CustomAttributes)

    //  *** End programmer edit section *** (ДомПоставщик CustomAttributes)
    [AutoAltered()]
    [Caption("Дом поставщик")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДомПоставщикE", new string[] {
            "Дом as \'Дом\'",
            "Дом.Address as \'Address\'",
            "Поставщик as \'Поставщик\'",
            "Поставщик.ИНН as \'ИНН\'"})]
    [View("ДомПоставщикL", new string[] {
            "Дом.Address as \'Address\'",
            "Поставщик.ИНН as \'ИНН\'"})]
    public class ДомПоставщик : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Umnyjj_dom.Дом fДом;
        
        private IIS.Umnyjj_dom.Поставщик fПоставщик;
        
        //  *** Start programmer edit section *** (ДомПоставщик CustomMembers)

        //  *** End programmer edit section *** (ДомПоставщик CustomMembers)

        
        /// <summary>
        /// Дом поставщик.
        /// </summary>
        //  *** Start programmer edit section *** (ДомПоставщик.Дом CustomAttributes)

        //  *** End programmer edit section *** (ДомПоставщик.Дом CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Дом Дом
        {
            get
            {
                //  *** Start programmer edit section *** (ДомПоставщик.Дом Get start)

                //  *** End programmer edit section *** (ДомПоставщик.Дом Get start)
                IIS.Umnyjj_dom.Дом result = this.fДом;
                //  *** Start programmer edit section *** (ДомПоставщик.Дом Get end)

                //  *** End programmer edit section *** (ДомПоставщик.Дом Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ДомПоставщик.Дом Set start)

                //  *** End programmer edit section *** (ДомПоставщик.Дом Set start)
                this.fДом = value;
                //  *** Start programmer edit section *** (ДомПоставщик.Дом Set end)

                //  *** End programmer edit section *** (ДомПоставщик.Дом Set end)
            }
        }
        
        /// <summary>
        /// Дом поставщик.
        /// </summary>
        //  *** Start programmer edit section *** (ДомПоставщик.Поставщик CustomAttributes)

        //  *** End programmer edit section *** (ДомПоставщик.Поставщик CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Поставщик Поставщик
        {
            get
            {
                //  *** Start programmer edit section *** (ДомПоставщик.Поставщик Get start)

                //  *** End programmer edit section *** (ДомПоставщик.Поставщик Get start)
                IIS.Umnyjj_dom.Поставщик result = this.fПоставщик;
                //  *** Start programmer edit section *** (ДомПоставщик.Поставщик Get end)

                //  *** End programmer edit section *** (ДомПоставщик.Поставщик Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ДомПоставщик.Поставщик Set start)

                //  *** End programmer edit section *** (ДомПоставщик.Поставщик Set start)
                this.fПоставщик = value;
                //  *** Start programmer edit section *** (ДомПоставщик.Поставщик Set end)

                //  *** End programmer edit section *** (ДомПоставщик.Поставщик Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДомПоставщикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомПоставщикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомПоставщикE", typeof(IIS.Umnyjj_dom.ДомПоставщик));
                }
            }
            
            /// <summary>
            /// "ДомПоставщикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомПоставщикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомПоставщикL", typeof(IIS.Umnyjj_dom.ДомПоставщик));
                }
            }
        }
    }
}
