//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Квитанция.
    /// </summary>
    //  *** Start programmer edit section *** (Квитанция CustomAttributes)

    //  *** End programmer edit section *** (Квитанция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КвитанцияE", new string[] {
            "Дата as \'Дата\'",
            "idTelePlus as \'Id tele plus\'",
            "Итого as \'Итого\'",
            "Помещение as \'Помещение\'",
            "Помещение.ТипПомещения as \'Тип помещения\'",
            "УправляющаяКомпания as \'Управляющая компания\'",
            "УправляющаяКомпания.Наименование as \'Наименование\'"})]
    [AssociatedDetailViewAttribute("КвитанцияE", "СтрокаКвитанции", "СтрокаКвитанцииE", true, "", "Строка квитанции", true, new string[] {
            ""})]
    [View("КвитанцияL", new string[] {
            "Дата as \'Дата\'",
            "idTelePlus as \'Id tele plus\'",
            "Итого as \'Итого\'",
            "Помещение.ТипПомещения as \'Тип помещения\'",
            "УправляющаяКомпания.Наименование as \'Наименование\'"})]
    public class Квитанция : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fidTelePlus;
        
        private string fИтого;
        
        private IIS.Umnyjj_dom.Помещение fПомещение;
        
        private IIS.Umnyjj_dom.УправляющаяКомпания fУправляющаяКомпания;
        
        private IIS.Umnyjj_dom.DetailArrayOfСтрокаКвитанции fСтрокаКвитанции;
        
        //  *** Start programmer edit section *** (Квитанция CustomMembers)

        //  *** End programmer edit section *** (Квитанция CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Квитанция.Дата CustomAttributes)

        //  *** End programmer edit section *** (Квитанция.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (Квитанция.Дата Get start)

                //  *** End programmer edit section *** (Квитанция.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (Квитанция.Дата Get end)

                //  *** End programmer edit section *** (Квитанция.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Квитанция.Дата Set start)

                //  *** End programmer edit section *** (Квитанция.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (Квитанция.Дата Set end)

                //  *** End programmer edit section *** (Квитанция.Дата Set end)
            }
        }
        
        /// <summary>
        /// idTelePlus.
        /// </summary>
        //  *** Start programmer edit section *** (Квитанция.idTelePlus CustomAttributes)

        //  *** End programmer edit section *** (Квитанция.idTelePlus CustomAttributes)
        public virtual int idTelePlus
        {
            get
            {
                //  *** Start programmer edit section *** (Квитанция.idTelePlus Get start)

                //  *** End programmer edit section *** (Квитанция.idTelePlus Get start)
                int result = this.fidTelePlus;
                //  *** Start programmer edit section *** (Квитанция.idTelePlus Get end)

                //  *** End programmer edit section *** (Квитанция.idTelePlus Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Квитанция.idTelePlus Set start)

                //  *** End programmer edit section *** (Квитанция.idTelePlus Set start)
                this.fidTelePlus = value;
                //  *** Start programmer edit section *** (Квитанция.idTelePlus Set end)

                //  *** End programmer edit section *** (Квитанция.idTelePlus Set end)
            }
        }
        
        /// <summary>
        /// Итого.
        /// </summary>
        //  *** Start programmer edit section *** (Квитанция.Итого CustomAttributes)

        //  *** End programmer edit section *** (Квитанция.Итого CustomAttributes)
        [StrLen(255)]
        public virtual string Итого
        {
            get
            {
                //  *** Start programmer edit section *** (Квитанция.Итого Get start)

                //  *** End programmer edit section *** (Квитанция.Итого Get start)
                string result = this.fИтого;
                //  *** Start programmer edit section *** (Квитанция.Итого Get end)

                //  *** End programmer edit section *** (Квитанция.Итого Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Квитанция.Итого Set start)

                //  *** End programmer edit section *** (Квитанция.Итого Set start)
                this.fИтого = value;
                //  *** Start programmer edit section *** (Квитанция.Итого Set end)

                //  *** End programmer edit section *** (Квитанция.Итого Set end)
            }
        }
        
        /// <summary>
        /// Квитанция.
        /// </summary>
        //  *** Start programmer edit section *** (Квитанция.Помещение CustomAttributes)

        //  *** End programmer edit section *** (Квитанция.Помещение CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Помещение Помещение
        {
            get
            {
                //  *** Start programmer edit section *** (Квитанция.Помещение Get start)

                //  *** End programmer edit section *** (Квитанция.Помещение Get start)
                IIS.Umnyjj_dom.Помещение result = this.fПомещение;
                //  *** Start programmer edit section *** (Квитанция.Помещение Get end)

                //  *** End programmer edit section *** (Квитанция.Помещение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Квитанция.Помещение Set start)

                //  *** End programmer edit section *** (Квитанция.Помещение Set start)
                this.fПомещение = value;
                //  *** Start programmer edit section *** (Квитанция.Помещение Set end)

                //  *** End programmer edit section *** (Квитанция.Помещение Set end)
            }
        }
        
        /// <summary>
        /// Квитанция.
        /// </summary>
        //  *** Start programmer edit section *** (Квитанция.УправляющаяКомпания CustomAttributes)

        //  *** End programmer edit section *** (Квитанция.УправляющаяКомпания CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.УправляющаяКомпания УправляющаяКомпания
        {
            get
            {
                //  *** Start programmer edit section *** (Квитанция.УправляющаяКомпания Get start)

                //  *** End programmer edit section *** (Квитанция.УправляющаяКомпания Get start)
                IIS.Umnyjj_dom.УправляющаяКомпания result = this.fУправляющаяКомпания;
                //  *** Start programmer edit section *** (Квитанция.УправляющаяКомпания Get end)

                //  *** End programmer edit section *** (Квитанция.УправляющаяКомпания Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Квитанция.УправляющаяКомпания Set start)

                //  *** End programmer edit section *** (Квитанция.УправляющаяКомпания Set start)
                this.fУправляющаяКомпания = value;
                //  *** Start programmer edit section *** (Квитанция.УправляющаяКомпания Set end)

                //  *** End programmer edit section *** (Квитанция.УправляющаяКомпания Set end)
            }
        }
        
        /// <summary>
        /// Квитанция.
        /// </summary>
        //  *** Start programmer edit section *** (Квитанция.СтрокаКвитанции CustomAttributes)

        //  *** End programmer edit section *** (Квитанция.СтрокаКвитанции CustomAttributes)
        public virtual IIS.Umnyjj_dom.DetailArrayOfСтрокаКвитанции СтрокаКвитанции
        {
            get
            {
                //  *** Start programmer edit section *** (Квитанция.СтрокаКвитанции Get start)

                //  *** End programmer edit section *** (Квитанция.СтрокаКвитанции Get start)
                if ((this.fСтрокаКвитанции == null))
                {
                    this.fСтрокаКвитанции = new IIS.Umnyjj_dom.DetailArrayOfСтрокаКвитанции(this);
                }
                IIS.Umnyjj_dom.DetailArrayOfСтрокаКвитанции result = this.fСтрокаКвитанции;
                //  *** Start programmer edit section *** (Квитанция.СтрокаКвитанции Get end)

                //  *** End programmer edit section *** (Квитанция.СтрокаКвитанции Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Квитанция.СтрокаКвитанции Set start)

                //  *** End programmer edit section *** (Квитанция.СтрокаКвитанции Set start)
                this.fСтрокаКвитанции = value;
                //  *** Start programmer edit section *** (Квитанция.СтрокаКвитанции Set end)

                //  *** End programmer edit section *** (Квитанция.СтрокаКвитанции Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КвитанцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвитанцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвитанцияE", typeof(IIS.Umnyjj_dom.Квитанция));
                }
            }
            
            /// <summary>
            /// "КвитанцияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвитанцияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвитанцияL", typeof(IIS.Umnyjj_dom.Квитанция));
                }
            }
        }
    }
}
