//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Модель ПУ.
    /// </summary>
    //  *** Start programmer edit section *** (МодельПУ CustomAttributes)

    //  *** End programmer edit section *** (МодельПУ CustomAttributes)
    [AutoAltered()]
    [Caption("Модель ПУ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МодельПУE", new string[] {
            "Наименование as \'Наименование\'",
            "Производитель as \'Производитель\'",
            "Актуальность as \'Актуальность\'"})]
    [View("МодельПУL", new string[] {
            "Наименование as \'Наименование\'",
            "Производитель as \'Производитель\'",
            "Актуальность as \'Актуальность\'"})]
    public class МодельПУ : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fПроизводитель;
        
        private bool fАктуальность;
        
        //  *** Start programmer edit section *** (МодельПУ CustomMembers)

        //  *** End programmer edit section *** (МодельПУ CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (МодельПУ.Наименование CustomAttributes)

        //  *** End programmer edit section *** (МодельПУ.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (МодельПУ.Наименование Get start)

                //  *** End programmer edit section *** (МодельПУ.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (МодельПУ.Наименование Get end)

                //  *** End programmer edit section *** (МодельПУ.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (МодельПУ.Наименование Set start)

                //  *** End programmer edit section *** (МодельПУ.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (МодельПУ.Наименование Set end)

                //  *** End programmer edit section *** (МодельПУ.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Производитель.
        /// </summary>
        //  *** Start programmer edit section *** (МодельПУ.Производитель CustomAttributes)

        //  *** End programmer edit section *** (МодельПУ.Производитель CustomAttributes)
        [StrLen(255)]
        public virtual string Производитель
        {
            get
            {
                //  *** Start programmer edit section *** (МодельПУ.Производитель Get start)

                //  *** End programmer edit section *** (МодельПУ.Производитель Get start)
                string result = this.fПроизводитель;
                //  *** Start programmer edit section *** (МодельПУ.Производитель Get end)

                //  *** End programmer edit section *** (МодельПУ.Производитель Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (МодельПУ.Производитель Set start)

                //  *** End programmer edit section *** (МодельПУ.Производитель Set start)
                this.fПроизводитель = value;
                //  *** Start programmer edit section *** (МодельПУ.Производитель Set end)

                //  *** End programmer edit section *** (МодельПУ.Производитель Set end)
            }
        }
        
        /// <summary>
        /// Актуальность.
        /// </summary>
        //  *** Start programmer edit section *** (МодельПУ.Актуальность CustomAttributes)

        //  *** End programmer edit section *** (МодельПУ.Актуальность CustomAttributes)
        public virtual bool Актуальность
        {
            get
            {
                //  *** Start programmer edit section *** (МодельПУ.Актуальность Get start)

                //  *** End programmer edit section *** (МодельПУ.Актуальность Get start)
                bool result = this.fАктуальность;
                //  *** Start programmer edit section *** (МодельПУ.Актуальность Get end)

                //  *** End programmer edit section *** (МодельПУ.Актуальность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (МодельПУ.Актуальность Set start)

                //  *** End programmer edit section *** (МодельПУ.Актуальность Set start)
                this.fАктуальность = value;
                //  *** Start programmer edit section *** (МодельПУ.Актуальность Set end)

                //  *** End programmer edit section *** (МодельПУ.Актуальность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МодельПУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МодельПУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МодельПУE", typeof(IIS.Umnyjj_dom.МодельПУ));
                }
            }
            
            /// <summary>
            /// "МодельПУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МодельПУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МодельПУL", typeof(IIS.Umnyjj_dom.МодельПУ));
                }
            }
        }
    }
}
