//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Показание ПУ.
    /// </summary>
    //  *** Start programmer edit section *** (ПоказаниеПУ CustomAttributes)

    //  *** End programmer edit section *** (ПоказаниеПУ CustomAttributes)
    [AutoAltered()]
    [Caption("Показание ПУ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоказаниеПУE", new string[] {
            "Значение as \'Значение\'",
            "Дата as \'Дата\'",
            "ПолученоАвтоматически as \'Получено автоматически\'",
            "ПриборУчета as \'Прибор учета\'",
            "ПриборУчета.Единица as \'Единица\'"})]
    [View("ПоказаниеПУL", new string[] {
            "Значение as \'Значение\'",
            "Дата as \'Дата\'",
            "ПолученоАвтоматически as \'Получено автоматически\'",
            "ПриборУчета.Единица as \'Единица\'"})]
    public class ПоказаниеПУ : ICSSoft.STORMNET.DataObject
    {
        
        private int fЗначение;
        
        private System.DateTime fДата;
        
        private bool fПолученоАвтоматически;
        
        private IIS.Umnyjj_dom.ПриборУчета fПриборУчета;
        
        //  *** Start programmer edit section *** (ПоказаниеПУ CustomMembers)

        //  *** End programmer edit section *** (ПоказаниеПУ CustomMembers)

        
        /// <summary>
        /// Значение.
        /// </summary>
        //  *** Start programmer edit section *** (ПоказаниеПУ.Значение CustomAttributes)

        //  *** End programmer edit section *** (ПоказаниеПУ.Значение CustomAttributes)
        public virtual int Значение
        {
            get
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.Значение Get start)

                //  *** End programmer edit section *** (ПоказаниеПУ.Значение Get start)
                int result = this.fЗначение;
                //  *** Start programmer edit section *** (ПоказаниеПУ.Значение Get end)

                //  *** End programmer edit section *** (ПоказаниеПУ.Значение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.Значение Set start)

                //  *** End programmer edit section *** (ПоказаниеПУ.Значение Set start)
                this.fЗначение = value;
                //  *** Start programmer edit section *** (ПоказаниеПУ.Значение Set end)

                //  *** End programmer edit section *** (ПоказаниеПУ.Значение Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (ПоказаниеПУ.Дата CustomAttributes)

        //  *** End programmer edit section *** (ПоказаниеПУ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.Дата Get start)

                //  *** End programmer edit section *** (ПоказаниеПУ.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (ПоказаниеПУ.Дата Get end)

                //  *** End programmer edit section *** (ПоказаниеПУ.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.Дата Set start)

                //  *** End programmer edit section *** (ПоказаниеПУ.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (ПоказаниеПУ.Дата Set end)

                //  *** End programmer edit section *** (ПоказаниеПУ.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПолученоАвтоматически.
        /// </summary>
        //  *** Start programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически CustomAttributes)

        //  *** End programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически CustomAttributes)
        public virtual bool ПолученоАвтоматически
        {
            get
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Get start)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Get start)
                bool result = this.fПолученоАвтоматически;
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Get end)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Set start)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Set start)
                this.fПолученоАвтоматически = value;
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Set end)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПолученоАвтоматически Set end)
            }
        }
        
        /// <summary>
        /// Показание ПУ.
        /// </summary>
        //  *** Start programmer edit section *** (ПоказаниеПУ.ПриборУчета CustomAttributes)

        //  *** End programmer edit section *** (ПоказаниеПУ.ПриборУчета CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.ПриборУчета ПриборУчета
        {
            get
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПриборУчета Get start)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПриборУчета Get start)
                IIS.Umnyjj_dom.ПриборУчета result = this.fПриборУчета;
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПриборУчета Get end)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПриборУчета Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПриборУчета Set start)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПриборУчета Set start)
                this.fПриборУчета = value;
                //  *** Start programmer edit section *** (ПоказаниеПУ.ПриборУчета Set end)

                //  *** End programmer edit section *** (ПоказаниеПУ.ПриборУчета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоказаниеПУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоказаниеПУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоказаниеПУE", typeof(IIS.Umnyjj_dom.ПоказаниеПУ));
                }
            }
            
            /// <summary>
            /// "ПоказаниеПУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоказаниеПУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоказаниеПУL", typeof(IIS.Umnyjj_dom.ПоказаниеПУ));
                }
            }
        }
    }
}
