//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Помещение.
    /// </summary>
    //  *** Start programmer edit section *** (Помещение CustomAttributes)

    //  *** End programmer edit section *** (Помещение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПомещениеE", new string[] {
            "Площадь as \'Площадь\'",
            "ТипПомещения as \'Тип помещения\'",
            "КолвоПроживающих as \'Колво проживающих\'",
            "Дом as \'Дом\'",
            "Дом.Address as \'Address\'",
            "АдресныйРеестр as \'Адресный реестр\'",
            "Собственник as \'Собственник\'",
            "Собственник.ФИО as \'ФИО\'"})]
    [View("ПомещениеL", new string[] {
            "Площадь as \'Площадь\'",
            "ТипПомещения as \'Тип помещения\'",
            "КолвоПроживающих as \'Колво проживающих\'",
            "Дом.Address as \'Address\'",
            "Собственник.ФИО as \'ФИО\'"})]
    public class Помещение : ICSSoft.STORMNET.DataObject
    {
        
        private int fПлощадь;
        
        private string fТипПомещения;
        
        private string fКолвоПроживающих;
        
        private IIS.Umnyjj_dom.Дом fДом;
        
        private IIS.Umnyjj_dom.АдресныйРеестр fАдресныйРеестр;
        
        private IIS.Umnyjj_dom.Собственник fСобственник;
        
        //  *** Start programmer edit section *** (Помещение CustomMembers)

        //  *** End programmer edit section *** (Помещение CustomMembers)

        
        /// <summary>
        /// Площадь.
        /// </summary>
        //  *** Start programmer edit section *** (Помещение.Площадь CustomAttributes)

        //  *** End programmer edit section *** (Помещение.Площадь CustomAttributes)
        public virtual int Площадь
        {
            get
            {
                //  *** Start programmer edit section *** (Помещение.Площадь Get start)

                //  *** End programmer edit section *** (Помещение.Площадь Get start)
                int result = this.fПлощадь;
                //  *** Start programmer edit section *** (Помещение.Площадь Get end)

                //  *** End programmer edit section *** (Помещение.Площадь Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Помещение.Площадь Set start)

                //  *** End programmer edit section *** (Помещение.Площадь Set start)
                this.fПлощадь = value;
                //  *** Start programmer edit section *** (Помещение.Площадь Set end)

                //  *** End programmer edit section *** (Помещение.Площадь Set end)
            }
        }
        
        /// <summary>
        /// ТипПомещения.
        /// </summary>
        //  *** Start programmer edit section *** (Помещение.ТипПомещения CustomAttributes)

        //  *** End programmer edit section *** (Помещение.ТипПомещения CustomAttributes)
        [StrLen(255)]
        public virtual string ТипПомещения
        {
            get
            {
                //  *** Start programmer edit section *** (Помещение.ТипПомещения Get start)

                //  *** End programmer edit section *** (Помещение.ТипПомещения Get start)
                string result = this.fТипПомещения;
                //  *** Start programmer edit section *** (Помещение.ТипПомещения Get end)

                //  *** End programmer edit section *** (Помещение.ТипПомещения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Помещение.ТипПомещения Set start)

                //  *** End programmer edit section *** (Помещение.ТипПомещения Set start)
                this.fТипПомещения = value;
                //  *** Start programmer edit section *** (Помещение.ТипПомещения Set end)

                //  *** End programmer edit section *** (Помещение.ТипПомещения Set end)
            }
        }
        
        /// <summary>
        /// КолвоПроживающих.
        /// </summary>
        //  *** Start programmer edit section *** (Помещение.КолвоПроживающих CustomAttributes)

        //  *** End programmer edit section *** (Помещение.КолвоПроживающих CustomAttributes)
        [StrLen(255)]
        public virtual string КолвоПроживающих
        {
            get
            {
                //  *** Start programmer edit section *** (Помещение.КолвоПроживающих Get start)

                //  *** End programmer edit section *** (Помещение.КолвоПроживающих Get start)
                string result = this.fКолвоПроживающих;
                //  *** Start programmer edit section *** (Помещение.КолвоПроживающих Get end)

                //  *** End programmer edit section *** (Помещение.КолвоПроживающих Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Помещение.КолвоПроживающих Set start)

                //  *** End programmer edit section *** (Помещение.КолвоПроживающих Set start)
                this.fКолвоПроживающих = value;
                //  *** Start programmer edit section *** (Помещение.КолвоПроживающих Set end)

                //  *** End programmer edit section *** (Помещение.КолвоПроживающих Set end)
            }
        }
        
        /// <summary>
        /// Помещение.
        /// </summary>
        //  *** Start programmer edit section *** (Помещение.Дом CustomAttributes)

        //  *** End programmer edit section *** (Помещение.Дом CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Дом Дом
        {
            get
            {
                //  *** Start programmer edit section *** (Помещение.Дом Get start)

                //  *** End programmer edit section *** (Помещение.Дом Get start)
                IIS.Umnyjj_dom.Дом result = this.fДом;
                //  *** Start programmer edit section *** (Помещение.Дом Get end)

                //  *** End programmer edit section *** (Помещение.Дом Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Помещение.Дом Set start)

                //  *** End programmer edit section *** (Помещение.Дом Set start)
                this.fДом = value;
                //  *** Start programmer edit section *** (Помещение.Дом Set end)

                //  *** End programmer edit section *** (Помещение.Дом Set end)
            }
        }
        
        /// <summary>
        /// Помещение.
        /// </summary>
        //  *** Start programmer edit section *** (Помещение.АдресныйРеестр CustomAttributes)

        //  *** End programmer edit section *** (Помещение.АдресныйРеестр CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.АдресныйРеестр АдресныйРеестр
        {
            get
            {
                //  *** Start programmer edit section *** (Помещение.АдресныйРеестр Get start)

                //  *** End programmer edit section *** (Помещение.АдресныйРеестр Get start)
                IIS.Umnyjj_dom.АдресныйРеестр result = this.fАдресныйРеестр;
                //  *** Start programmer edit section *** (Помещение.АдресныйРеестр Get end)

                //  *** End programmer edit section *** (Помещение.АдресныйРеестр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Помещение.АдресныйРеестр Set start)

                //  *** End programmer edit section *** (Помещение.АдресныйРеестр Set start)
                this.fАдресныйРеестр = value;
                //  *** Start programmer edit section *** (Помещение.АдресныйРеестр Set end)

                //  *** End programmer edit section *** (Помещение.АдресныйРеестр Set end)
            }
        }
        
        /// <summary>
        /// Помещение.
        /// </summary>
        //  *** Start programmer edit section *** (Помещение.Собственник CustomAttributes)

        //  *** End programmer edit section *** (Помещение.Собственник CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Собственник Собственник
        {
            get
            {
                //  *** Start programmer edit section *** (Помещение.Собственник Get start)

                //  *** End programmer edit section *** (Помещение.Собственник Get start)
                IIS.Umnyjj_dom.Собственник result = this.fСобственник;
                //  *** Start programmer edit section *** (Помещение.Собственник Get end)

                //  *** End programmer edit section *** (Помещение.Собственник Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Помещение.Собственник Set start)

                //  *** End programmer edit section *** (Помещение.Собственник Set start)
                this.fСобственник = value;
                //  *** Start programmer edit section *** (Помещение.Собственник Set end)

                //  *** End programmer edit section *** (Помещение.Собственник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПомещениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПомещениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПомещениеE", typeof(IIS.Umnyjj_dom.Помещение));
                }
            }
            
            /// <summary>
            /// "ПомещениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПомещениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПомещениеL", typeof(IIS.Umnyjj_dom.Помещение));
                }
            }
        }
    }
}
