//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поставщик.
    /// </summary>
    //  *** Start programmer edit section *** (Поставщик CustomAttributes)

    //  *** End programmer edit section *** (Поставщик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоставщикE", new string[] {
            "ИНН as \'ИНН\'",
            "Наименование as \'Наименование\'",
            "РасчетныйСчет as \'Расчетный счет\'",
            "Описание as \'Описание\'"})]
    [View("ПоставщикL", new string[] {
            "ИНН as \'ИНН\'",
            "Наименование as \'Наименование\'",
            "РасчетныйСчет as \'Расчетный счет\'",
            "Описание as \'Описание\'"})]
    public class Поставщик : ICSSoft.STORMNET.DataObject
    {
        
        private string fИНН;
        
        private string fНаименование;
        
        private int fРасчетныйСчет;
        
        private string fОписание;
        
        //  *** Start programmer edit section *** (Поставщик CustomMembers)

        //  *** End programmer edit section *** (Поставщик CustomMembers)

        
        /// <summary>
        /// ИНН.
        /// </summary>
        //  *** Start programmer edit section *** (Поставщик.ИНН CustomAttributes)

        //  *** End programmer edit section *** (Поставщик.ИНН CustomAttributes)
        [StrLen(255)]
        public virtual string ИНН
        {
            get
            {
                //  *** Start programmer edit section *** (Поставщик.ИНН Get start)

                //  *** End programmer edit section *** (Поставщик.ИНН Get start)
                string result = this.fИНН;
                //  *** Start programmer edit section *** (Поставщик.ИНН Get end)

                //  *** End programmer edit section *** (Поставщик.ИНН Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Поставщик.ИНН Set start)

                //  *** End programmer edit section *** (Поставщик.ИНН Set start)
                this.fИНН = value;
                //  *** Start programmer edit section *** (Поставщик.ИНН Set end)

                //  *** End programmer edit section *** (Поставщик.ИНН Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Поставщик.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Поставщик.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Поставщик.Наименование Get start)

                //  *** End programmer edit section *** (Поставщик.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Поставщик.Наименование Get end)

                //  *** End programmer edit section *** (Поставщик.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Поставщик.Наименование Set start)

                //  *** End programmer edit section *** (Поставщик.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Поставщик.Наименование Set end)

                //  *** End programmer edit section *** (Поставщик.Наименование Set end)
            }
        }
        
        /// <summary>
        /// РасчетныйСчет.
        /// </summary>
        //  *** Start programmer edit section *** (Поставщик.РасчетныйСчет CustomAttributes)

        //  *** End programmer edit section *** (Поставщик.РасчетныйСчет CustomAttributes)
        public virtual int РасчетныйСчет
        {
            get
            {
                //  *** Start programmer edit section *** (Поставщик.РасчетныйСчет Get start)

                //  *** End programmer edit section *** (Поставщик.РасчетныйСчет Get start)
                int result = this.fРасчетныйСчет;
                //  *** Start programmer edit section *** (Поставщик.РасчетныйСчет Get end)

                //  *** End programmer edit section *** (Поставщик.РасчетныйСчет Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Поставщик.РасчетныйСчет Set start)

                //  *** End programmer edit section *** (Поставщик.РасчетныйСчет Set start)
                this.fРасчетныйСчет = value;
                //  *** Start programmer edit section *** (Поставщик.РасчетныйСчет Set end)

                //  *** End programmer edit section *** (Поставщик.РасчетныйСчет Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        //  *** Start programmer edit section *** (Поставщик.Описание CustomAttributes)

        //  *** End programmer edit section *** (Поставщик.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                //  *** Start programmer edit section *** (Поставщик.Описание Get start)

                //  *** End programmer edit section *** (Поставщик.Описание Get start)
                string result = this.fОписание;
                //  *** Start programmer edit section *** (Поставщик.Описание Get end)

                //  *** End programmer edit section *** (Поставщик.Описание Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Поставщик.Описание Set start)

                //  *** End programmer edit section *** (Поставщик.Описание Set start)
                this.fОписание = value;
                //  *** Start programmer edit section *** (Поставщик.Описание Set end)

                //  *** End programmer edit section *** (Поставщик.Описание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоставщикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикE", typeof(IIS.Umnyjj_dom.Поставщик));
                }
            }
            
            /// <summary>
            /// "ПоставщикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставщикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставщикL", typeof(IIS.Umnyjj_dom.Поставщик));
                }
            }
        }
    }
}
