//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Помещение собственника.
    /// </summary>
    //  *** Start programmer edit section *** (ПомещениеСобственника CustomAttributes)

    //  *** End programmer edit section *** (ПомещениеСобственника CustomAttributes)
    [AutoAltered()]
    [Caption("Помещение собственника")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПомещениеСобственникаE", new string[] {
            "ОсновнойСобственник as \'Основной собственник\'",
            "ДоляСобственности as \'Доля собственности\'",
            "Помещение as \'Помещение\'",
            "Помещение.ТипПомещения as \'Тип помещения\'"}, Hidden=new string[] {
            "Помещение.ТипПомещения"})]
    [MasterViewDefineAttribute("ПомещениеСобственникаE", "Помещение", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипПомещения")]
    public class ПомещениеСобственника : ICSSoft.STORMNET.DataObject
    {
        
        private string fОсновнойСобственник;
        
        private string fДоляСобственности;
        
        private IIS.Umnyjj_dom.Помещение fПомещение;
        
        private IIS.Umnyjj_dom.Собственник fСобственник;
        
        //  *** Start programmer edit section *** (ПомещениеСобственника CustomMembers)

        //  *** End programmer edit section *** (ПомещениеСобственника CustomMembers)

        
        /// <summary>
        /// ОсновнойСобственник.
        /// </summary>
        //  *** Start programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник CustomAttributes)

        //  *** End programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник CustomAttributes)
        [StrLen(255)]
        public virtual string ОсновнойСобственник
        {
            get
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Get start)

                //  *** End programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Get start)
                string result = this.fОсновнойСобственник;
                //  *** Start programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Get end)

                //  *** End programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Set start)

                //  *** End programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Set start)
                this.fОсновнойСобственник = value;
                //  *** Start programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Set end)

                //  *** End programmer edit section *** (ПомещениеСобственника.ОсновнойСобственник Set end)
            }
        }
        
        /// <summary>
        /// ДоляСобственности.
        /// </summary>
        //  *** Start programmer edit section *** (ПомещениеСобственника.ДоляСобственности CustomAttributes)

        //  *** End programmer edit section *** (ПомещениеСобственника.ДоляСобственности CustomAttributes)
        [StrLen(255)]
        public virtual string ДоляСобственности
        {
            get
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.ДоляСобственности Get start)

                //  *** End programmer edit section *** (ПомещениеСобственника.ДоляСобственности Get start)
                string result = this.fДоляСобственности;
                //  *** Start programmer edit section *** (ПомещениеСобственника.ДоляСобственности Get end)

                //  *** End programmer edit section *** (ПомещениеСобственника.ДоляСобственности Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.ДоляСобственности Set start)

                //  *** End programmer edit section *** (ПомещениеСобственника.ДоляСобственности Set start)
                this.fДоляСобственности = value;
                //  *** Start programmer edit section *** (ПомещениеСобственника.ДоляСобственности Set end)

                //  *** End programmer edit section *** (ПомещениеСобственника.ДоляСобственности Set end)
            }
        }
        
        /// <summary>
        /// Помещение собственника.
        /// </summary>
        //  *** Start programmer edit section *** (ПомещениеСобственника.Помещение CustomAttributes)

        //  *** End programmer edit section *** (ПомещениеСобственника.Помещение CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Помещение Помещение
        {
            get
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.Помещение Get start)

                //  *** End programmer edit section *** (ПомещениеСобственника.Помещение Get start)
                IIS.Umnyjj_dom.Помещение result = this.fПомещение;
                //  *** Start programmer edit section *** (ПомещениеСобственника.Помещение Get end)

                //  *** End programmer edit section *** (ПомещениеСобственника.Помещение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.Помещение Set start)

                //  *** End programmer edit section *** (ПомещениеСобственника.Помещение Set start)
                this.fПомещение = value;
                //  *** Start programmer edit section *** (ПомещениеСобственника.Помещение Set end)

                //  *** End programmer edit section *** (ПомещениеСобственника.Помещение Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Umnyjj_dom.Собственник.
        /// </summary>
        //  *** Start programmer edit section *** (ПомещениеСобственника.Собственник CustomAttributes)

        //  *** End programmer edit section *** (ПомещениеСобственника.Собственник CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Собственник Собственник
        {
            get
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.Собственник Get start)

                //  *** End programmer edit section *** (ПомещениеСобственника.Собственник Get start)
                IIS.Umnyjj_dom.Собственник result = this.fСобственник;
                //  *** Start programmer edit section *** (ПомещениеСобственника.Собственник Get end)

                //  *** End programmer edit section *** (ПомещениеСобственника.Собственник Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПомещениеСобственника.Собственник Set start)

                //  *** End programmer edit section *** (ПомещениеСобственника.Собственник Set start)
                this.fСобственник = value;
                //  *** Start programmer edit section *** (ПомещениеСобственника.Собственник Set end)

                //  *** End programmer edit section *** (ПомещениеСобственника.Собственник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПомещениеСобственникаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПомещениеСобственникаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПомещениеСобственникаE", typeof(IIS.Umnyjj_dom.ПомещениеСобственника));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПомещениеСобственника.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfПомещениеСобственника CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfПомещениеСобственника CustomAttributes)
    public class DetailArrayOfПомещениеСобственника : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Umnyjj_dom.DetailArrayOfПомещениеСобственника members)

        //  *** End programmer edit section *** (IIS.Umnyjj_dom.DetailArrayOfПомещениеСобственника members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПомещениеСобственника by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПомещениеСобственника.
        /// </summary>
        public DetailArrayOfПомещениеСобственника(IIS.Umnyjj_dom.Собственник fСобственник) : 
                base(typeof(ПомещениеСобственника), ((ICSSoft.STORMNET.DataObject)(fСобственник)))
        {
        }
        
        public IIS.Umnyjj_dom.ПомещениеСобственника this[int index]
        {
            get
            {
                return ((IIS.Umnyjj_dom.ПомещениеСобственника)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Umnyjj_dom.ПомещениеСобственника dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
