//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прибор учета.
    /// </summary>
    //  *** Start programmer edit section *** (ПриборУчета CustomAttributes)

    //  *** End programmer edit section *** (ПриборУчета CustomAttributes)
    [AutoAltered()]
    [Caption("Прибор учета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриборУчетаE", new string[] {
            "Единица as \'Единица\'",
            "ДатаУстановки as \'Дата установки\'",
            "ДатаСнятия as \'Дата снятия\'",
            "Актуальность as \'Актуальность\'",
            "АвтоматическаяПередача as \'Автоматическая передача\'",
            "МодельПУ as \'Модель ПУ\'",
            "МодельПУ.Наименование as \'Наименование\'",
            "Помещение as \'Помещение\'",
            "Помещение.ТипПомещения as \'Тип помещения\'"})]
    [View("ПриборУчетаL", new string[] {
            "Единица as \'Единица\'",
            "ДатаУстановки as \'Дата установки\'",
            "ДатаСнятия as \'Дата снятия\'",
            "Актуальность as \'Актуальность\'",
            "АвтоматическаяПередача as \'Автоматическая передача\'",
            "МодельПУ.Наименование as \'Наименование\'",
            "Помещение.ТипПомещения as \'Тип помещения\'"})]
    public class ПриборУчета : ICSSoft.STORMNET.DataObject
    {
        
        private string fЕдиница;
        
        private System.DateTime fДатаУстановки;
        
        private System.DateTime fДатаСнятия;
        
        private bool fАктуальность;
        
        private bool fАвтоматическаяПередача;
        
        private IIS.Umnyjj_dom.МодельПУ fМодельПУ;
        
        private IIS.Umnyjj_dom.Помещение fПомещение;
        
        //  *** Start programmer edit section *** (ПриборУчета CustomMembers)

        //  *** End programmer edit section *** (ПриборУчета CustomMembers)

        
        /// <summary>
        /// Единица.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.Единица CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.Единица CustomAttributes)
        [StrLen(255)]
        public virtual string Единица
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.Единица Get start)

                //  *** End programmer edit section *** (ПриборУчета.Единица Get start)
                string result = this.fЕдиница;
                //  *** Start programmer edit section *** (ПриборУчета.Единица Get end)

                //  *** End programmer edit section *** (ПриборУчета.Единица Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.Единица Set start)

                //  *** End programmer edit section *** (ПриборУчета.Единица Set start)
                this.fЕдиница = value;
                //  *** Start programmer edit section *** (ПриборУчета.Единица Set end)

                //  *** End programmer edit section *** (ПриборУчета.Единица Set end)
            }
        }
        
        /// <summary>
        /// ДатаУстановки.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.ДатаУстановки CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.ДатаУстановки CustomAttributes)
        public virtual System.DateTime ДатаУстановки
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.ДатаУстановки Get start)

                //  *** End programmer edit section *** (ПриборУчета.ДатаУстановки Get start)
                System.DateTime result = this.fДатаУстановки;
                //  *** Start programmer edit section *** (ПриборУчета.ДатаУстановки Get end)

                //  *** End programmer edit section *** (ПриборУчета.ДатаУстановки Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.ДатаУстановки Set start)

                //  *** End programmer edit section *** (ПриборУчета.ДатаУстановки Set start)
                this.fДатаУстановки = value;
                //  *** Start programmer edit section *** (ПриборУчета.ДатаУстановки Set end)

                //  *** End programmer edit section *** (ПриборУчета.ДатаУстановки Set end)
            }
        }
        
        /// <summary>
        /// ДатаСнятия.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.ДатаСнятия CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.ДатаСнятия CustomAttributes)
        public virtual System.DateTime ДатаСнятия
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.ДатаСнятия Get start)

                //  *** End programmer edit section *** (ПриборУчета.ДатаСнятия Get start)
                System.DateTime result = this.fДатаСнятия;
                //  *** Start programmer edit section *** (ПриборУчета.ДатаСнятия Get end)

                //  *** End programmer edit section *** (ПриборУчета.ДатаСнятия Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.ДатаСнятия Set start)

                //  *** End programmer edit section *** (ПриборУчета.ДатаСнятия Set start)
                this.fДатаСнятия = value;
                //  *** Start programmer edit section *** (ПриборУчета.ДатаСнятия Set end)

                //  *** End programmer edit section *** (ПриборУчета.ДатаСнятия Set end)
            }
        }
        
        /// <summary>
        /// Актуальность.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.Актуальность CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.Актуальность CustomAttributes)
        public virtual bool Актуальность
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.Актуальность Get start)

                //  *** End programmer edit section *** (ПриборУчета.Актуальность Get start)
                bool result = this.fАктуальность;
                //  *** Start programmer edit section *** (ПриборУчета.Актуальность Get end)

                //  *** End programmer edit section *** (ПриборУчета.Актуальность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.Актуальность Set start)

                //  *** End programmer edit section *** (ПриборУчета.Актуальность Set start)
                this.fАктуальность = value;
                //  *** Start programmer edit section *** (ПриборУчета.Актуальность Set end)

                //  *** End programmer edit section *** (ПриборУчета.Актуальность Set end)
            }
        }
        
        /// <summary>
        /// АвтоматическаяПередача.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.АвтоматическаяПередача CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.АвтоматическаяПередача CustomAttributes)
        public virtual bool АвтоматическаяПередача
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.АвтоматическаяПередача Get start)

                //  *** End programmer edit section *** (ПриборУчета.АвтоматическаяПередача Get start)
                bool result = this.fАвтоматическаяПередача;
                //  *** Start programmer edit section *** (ПриборУчета.АвтоматическаяПередача Get end)

                //  *** End programmer edit section *** (ПриборУчета.АвтоматическаяПередача Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.АвтоматическаяПередача Set start)

                //  *** End programmer edit section *** (ПриборУчета.АвтоматическаяПередача Set start)
                this.fАвтоматическаяПередача = value;
                //  *** Start programmer edit section *** (ПриборУчета.АвтоматическаяПередача Set end)

                //  *** End programmer edit section *** (ПриборУчета.АвтоматическаяПередача Set end)
            }
        }
        
        /// <summary>
        /// Прибор учета.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.МодельПУ CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.МодельПУ CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.МодельПУ МодельПУ
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.МодельПУ Get start)

                //  *** End programmer edit section *** (ПриборУчета.МодельПУ Get start)
                IIS.Umnyjj_dom.МодельПУ result = this.fМодельПУ;
                //  *** Start programmer edit section *** (ПриборУчета.МодельПУ Get end)

                //  *** End programmer edit section *** (ПриборУчета.МодельПУ Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.МодельПУ Set start)

                //  *** End programmer edit section *** (ПриборУчета.МодельПУ Set start)
                this.fМодельПУ = value;
                //  *** Start programmer edit section *** (ПриборУчета.МодельПУ Set end)

                //  *** End programmer edit section *** (ПриборУчета.МодельПУ Set end)
            }
        }
        
        /// <summary>
        /// Прибор учета.
        /// </summary>
        //  *** Start programmer edit section *** (ПриборУчета.Помещение CustomAttributes)

        //  *** End programmer edit section *** (ПриборУчета.Помещение CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Помещение Помещение
        {
            get
            {
                //  *** Start programmer edit section *** (ПриборУчета.Помещение Get start)

                //  *** End programmer edit section *** (ПриборУчета.Помещение Get start)
                IIS.Umnyjj_dom.Помещение result = this.fПомещение;
                //  *** Start programmer edit section *** (ПриборУчета.Помещение Get end)

                //  *** End programmer edit section *** (ПриборУчета.Помещение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПриборУчета.Помещение Set start)

                //  *** End programmer edit section *** (ПриборУчета.Помещение Set start)
                this.fПомещение = value;
                //  *** Start programmer edit section *** (ПриборУчета.Помещение Set end)

                //  *** End programmer edit section *** (ПриборУчета.Помещение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриборУчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборУчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборУчетаE", typeof(IIS.Umnyjj_dom.ПриборУчета));
                }
            }
            
            /// <summary>
            /// "ПриборУчетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборУчетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборУчетаL", typeof(IIS.Umnyjj_dom.ПриборУчета));
                }
            }
        }
    }
}
