//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Собственник.
    /// </summary>
    //  *** Start programmer edit section *** (Собственник CustomAttributes)

    //  *** End programmer edit section *** (Собственник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СобственникE", new string[] {
            "ФИО as \'ФИО\'",
            "идТелеПлюс as \'Ид теле плюс\'"})]
    [AssociatedDetailViewAttribute("СобственникE", "ПомещениеСобственника", "ПомещениеСобственникаE", true, "", "Помещение собственника", true, new string[] {
            ""})]
    [View("СобственникL", new string[] {
            "ФИО as \'ФИО\'",
            "идТелеПлюс as \'Ид теле плюс\'"})]
    public class Собственник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fидТелеПлюс;
        
        private IIS.Umnyjj_dom.DetailArrayOfПомещениеСобственника fПомещениеСобственника;
        
        //  *** Start programmer edit section *** (Собственник CustomMembers)

        //  *** End programmer edit section *** (Собственник CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (Собственник.ФИО CustomAttributes)

        //  *** End programmer edit section *** (Собственник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (Собственник.ФИО Get start)

                //  *** End programmer edit section *** (Собственник.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (Собственник.ФИО Get end)

                //  *** End programmer edit section *** (Собственник.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Собственник.ФИО Set start)

                //  *** End programmer edit section *** (Собственник.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (Собственник.ФИО Set end)

                //  *** End programmer edit section *** (Собственник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// идТелеПлюс.
        /// </summary>
        //  *** Start programmer edit section *** (Собственник.идТелеПлюс CustomAttributes)

        //  *** End programmer edit section *** (Собственник.идТелеПлюс CustomAttributes)
        public virtual int идТелеПлюс
        {
            get
            {
                //  *** Start programmer edit section *** (Собственник.идТелеПлюс Get start)

                //  *** End programmer edit section *** (Собственник.идТелеПлюс Get start)
                int result = this.fидТелеПлюс;
                //  *** Start programmer edit section *** (Собственник.идТелеПлюс Get end)

                //  *** End programmer edit section *** (Собственник.идТелеПлюс Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Собственник.идТелеПлюс Set start)

                //  *** End programmer edit section *** (Собственник.идТелеПлюс Set start)
                this.fидТелеПлюс = value;
                //  *** Start programmer edit section *** (Собственник.идТелеПлюс Set end)

                //  *** End programmer edit section *** (Собственник.идТелеПлюс Set end)
            }
        }
        
        /// <summary>
        /// Собственник.
        /// </summary>
        //  *** Start programmer edit section *** (Собственник.ПомещениеСобственника CustomAttributes)

        //  *** End programmer edit section *** (Собственник.ПомещениеСобственника CustomAttributes)
        public virtual IIS.Umnyjj_dom.DetailArrayOfПомещениеСобственника ПомещениеСобственника
        {
            get
            {
                //  *** Start programmer edit section *** (Собственник.ПомещениеСобственника Get start)

                //  *** End programmer edit section *** (Собственник.ПомещениеСобственника Get start)
                if ((this.fПомещениеСобственника == null))
                {
                    this.fПомещениеСобственника = new IIS.Umnyjj_dom.DetailArrayOfПомещениеСобственника(this);
                }
                IIS.Umnyjj_dom.DetailArrayOfПомещениеСобственника result = this.fПомещениеСобственника;
                //  *** Start programmer edit section *** (Собственник.ПомещениеСобственника Get end)

                //  *** End programmer edit section *** (Собственник.ПомещениеСобственника Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Собственник.ПомещениеСобственника Set start)

                //  *** End programmer edit section *** (Собственник.ПомещениеСобственника Set start)
                this.fПомещениеСобственника = value;
                //  *** Start programmer edit section *** (Собственник.ПомещениеСобственника Set end)

                //  *** End programmer edit section *** (Собственник.ПомещениеСобственника Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СобственникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СобственникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СобственникE", typeof(IIS.Umnyjj_dom.Собственник));
                }
            }
            
            /// <summary>
            /// "СобственникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СобственникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СобственникL", typeof(IIS.Umnyjj_dom.Собственник));
                }
            }
        }
    }
}
