//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    //  *** Start programmer edit section *** (Сотрудник CustomAttributes)

    //  *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "ФИО as \'ФИО\'",
            "УправляющаяКомпания as \'Управляющая компания\'",
            "УправляющаяКомпания.Наименование as \'Наименование\'"})]
    [View("СотрудникL", new string[] {
            "ФИО as \'ФИО\'",
            "УправляющаяКомпания.Наименование as \'Наименование\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Umnyjj_dom.УправляющаяКомпания fУправляющаяКомпания;
        
        //  *** Start programmer edit section *** (Сотрудник CustomMembers)

        //  *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (Сотрудник.ФИО CustomAttributes)

        //  *** End programmer edit section *** (Сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (Сотрудник.ФИО Get start)

                //  *** End programmer edit section *** (Сотрудник.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (Сотрудник.ФИО Get end)

                //  *** End programmer edit section *** (Сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Сотрудник.ФИО Set start)

                //  *** End programmer edit section *** (Сотрудник.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (Сотрудник.ФИО Set end)

                //  *** End programmer edit section *** (Сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        //  *** Start programmer edit section *** (Сотрудник.УправляющаяКомпания CustomAttributes)

        //  *** End programmer edit section *** (Сотрудник.УправляющаяКомпания CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.УправляющаяКомпания УправляющаяКомпания
        {
            get
            {
                //  *** Start programmer edit section *** (Сотрудник.УправляющаяКомпания Get start)

                //  *** End programmer edit section *** (Сотрудник.УправляющаяКомпания Get start)
                IIS.Umnyjj_dom.УправляющаяКомпания result = this.fУправляющаяКомпания;
                //  *** Start programmer edit section *** (Сотрудник.УправляющаяКомпания Get end)

                //  *** End programmer edit section *** (Сотрудник.УправляющаяКомпания Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Сотрудник.УправляющаяКомпания Set start)

                //  *** End programmer edit section *** (Сотрудник.УправляющаяКомпания Set start)
                this.fУправляющаяКомпания = value;
                //  *** Start programmer edit section *** (Сотрудник.УправляющаяКомпания Set end)

                //  *** End programmer edit section *** (Сотрудник.УправляющаяКомпания Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.Umnyjj_dom.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.Umnyjj_dom.Сотрудник));
                }
            }
        }
    }
}
