//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка квитанции.
    /// </summary>
    //  *** Start programmer edit section *** (СтрокаКвитанции CustomAttributes)

    //  *** End programmer edit section *** (СтрокаКвитанции CustomAttributes)
    [AutoAltered()]
    [Caption("Строка квитанции")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтрокаКвитанцииE", new string[] {
            "Расход as \'Расход\'",
            "Единица as \'Единица\'",
            "Сумма as \'Сумма\'",
            "Расшифровка as \'Расшифровка\'",
            "Комментарий as \'Комментарий\'",
            "ПоказаниеПУ as \'Показание ПУ\'",
            "ПоказаниеПУ.Значение as \'Значение\'",
            "Тариф as \'Тариф\'",
            "Тариф.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ПоказаниеПУ.Значение",
            "Тариф.Наименование"})]
    [MasterViewDefineAttribute("СтрокаКвитанцииE", "ПоказаниеПУ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Значение")]
    [MasterViewDefineAttribute("СтрокаКвитанцииE", "Тариф", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СтрокаКвитанции : ICSSoft.STORMNET.DataObject
    {
        
        private int fРасход;
        
        private string fЕдиница;
        
        private int fСумма;
        
        private string fРасшифровка;
        
        private string fКомментарий;
        
        private IIS.Umnyjj_dom.ПоказаниеПУ fПоказаниеПУ;
        
        private IIS.Umnyjj_dom.Тариф fТариф;
        
        private IIS.Umnyjj_dom.Квитанция fКвитанция;
        
        //  *** Start programmer edit section *** (СтрокаКвитанции CustomMembers)

        //  *** End programmer edit section *** (СтрокаКвитанции CustomMembers)

        
        /// <summary>
        /// Расход.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Расход CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Расход CustomAttributes)
        public virtual int Расход
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расход Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расход Get start)
                int result = this.fРасход;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расход Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расход Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расход Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расход Set start)
                this.fРасход = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расход Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расход Set end)
            }
        }
        
        /// <summary>
        /// Единица.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Единица CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Единица CustomAttributes)
        [StrLen(255)]
        public virtual string Единица
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Единица Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Единица Get start)
                string result = this.fЕдиница;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Единица Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Единица Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Единица Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Единица Set start)
                this.fЕдиница = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Единица Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Единица Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Сумма CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Сумма Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Сумма Get start)
                int result = this.fСумма;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Сумма Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Сумма Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Сумма Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Сумма Set start)
                this.fСумма = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Сумма Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Расшифровка.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Расшифровка CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Расшифровка CustomAttributes)
        [StrLen(255)]
        public virtual string Расшифровка
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расшифровка Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расшифровка Get start)
                string result = this.fРасшифровка;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расшифровка Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расшифровка Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расшифровка Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расшифровка Set start)
                this.fРасшифровка = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Расшифровка Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Расшифровка Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Комментарий CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Комментарий Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Комментарий Get start)
                string result = this.fКомментарий;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Комментарий Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Комментарий Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Комментарий Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Комментарий Set start)
                this.fКомментарий = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Комментарий Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Строка квитанции.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.ПоказаниеПУ ПоказаниеПУ
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Get start)
                IIS.Umnyjj_dom.ПоказаниеПУ result = this.fПоказаниеПУ;
                //  *** Start programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Set start)
                this.fПоказаниеПУ = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.ПоказаниеПУ Set end)
            }
        }
        
        /// <summary>
        /// Строка квитанции.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Тариф CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Тариф CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Тариф Тариф
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Тариф Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Тариф Get start)
                IIS.Umnyjj_dom.Тариф result = this.fТариф;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Тариф Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Тариф Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Тариф Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Тариф Set start)
                this.fТариф = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Тариф Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Тариф Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Umnyjj_dom.Квитанция.
        /// </summary>
        //  *** Start programmer edit section *** (СтрокаКвитанции.Квитанция CustomAttributes)

        //  *** End programmer edit section *** (СтрокаКвитанции.Квитанция CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Квитанция Квитанция
        {
            get
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Квитанция Get start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Квитанция Get start)
                IIS.Umnyjj_dom.Квитанция result = this.fКвитанция;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Квитанция Get end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Квитанция Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (СтрокаКвитанции.Квитанция Set start)

                //  *** End programmer edit section *** (СтрокаКвитанции.Квитанция Set start)
                this.fКвитанция = value;
                //  *** Start programmer edit section *** (СтрокаКвитанции.Квитанция Set end)

                //  *** End programmer edit section *** (СтрокаКвитанции.Квитанция Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтрокаКвитанцииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаКвитанцииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаКвитанцииE", typeof(IIS.Umnyjj_dom.СтрокаКвитанции));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СтрокаКвитанции.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрокаКвитанции CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfСтрокаКвитанции CustomAttributes)
    public class DetailArrayOfСтрокаКвитанции : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Umnyjj_dom.DetailArrayOfСтрокаКвитанции members)

        //  *** End programmer edit section *** (IIS.Umnyjj_dom.DetailArrayOfСтрокаКвитанции members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СтрокаКвитанции by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СтрокаКвитанции.
        /// </summary>
        public DetailArrayOfСтрокаКвитанции(IIS.Umnyjj_dom.Квитанция fКвитанция) : 
                base(typeof(СтрокаКвитанции), ((ICSSoft.STORMNET.DataObject)(fКвитанция)))
        {
        }
        
        public IIS.Umnyjj_dom.СтрокаКвитанции this[int index]
        {
            get
            {
                return ((IIS.Umnyjj_dom.СтрокаКвитанции)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Umnyjj_dom.СтрокаКвитанции dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
