//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тариф.
    /// </summary>
    //  *** Start programmer edit section *** (Тариф CustomAttributes)

    //  *** End programmer edit section *** (Тариф CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТарифE", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Единица as \'Единица\'",
            "Формула as \'Формула\'",
            "Стоимость as \'Стоимость\'",
            "ВидУслуги as \'Вид услуги\'",
            "ВидУслуги.Наименование as \'Наименование\'",
            "Поставщик as \'Поставщик\'",
            "Поставщик.ИНН as \'ИНН\'"})]
    [View("ТарифL", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Единица as \'Единица\'",
            "Формула as \'Формула\'",
            "Стоимость as \'Стоимость\'",
            "ВидУслуги.Наименование as \'Наименование\'",
            "Поставщик.ИНН as \'ИНН\'"})]
    public class Тариф : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fОписание;
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаОкончания;
        
        private string fЕдиница;
        
        private string fФормула;
        
        private string fСтоимость;
        
        private IIS.Umnyjj_dom.ВидУслуги fВидУслуги;
        
        private IIS.Umnyjj_dom.Поставщик fПоставщик;
        
        //  *** Start programmer edit section *** (Тариф CustomMembers)

        //  *** End programmer edit section *** (Тариф CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Тариф.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.Наименование Get start)

                //  *** End programmer edit section *** (Тариф.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Тариф.Наименование Get end)

                //  *** End programmer edit section *** (Тариф.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.Наименование Set start)

                //  *** End programmer edit section *** (Тариф.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Тариф.Наименование Set end)

                //  *** End programmer edit section *** (Тариф.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.Описание CustomAttributes)

        //  *** End programmer edit section *** (Тариф.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.Описание Get start)

                //  *** End programmer edit section *** (Тариф.Описание Get start)
                string result = this.fОписание;
                //  *** Start programmer edit section *** (Тариф.Описание Get end)

                //  *** End programmer edit section *** (Тариф.Описание Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.Описание Set start)

                //  *** End programmer edit section *** (Тариф.Описание Set start)
                this.fОписание = value;
                //  *** Start programmer edit section *** (Тариф.Описание Set end)

                //  *** End programmer edit section *** (Тариф.Описание Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.ДатаНачала CustomAttributes)

        //  *** End programmer edit section *** (Тариф.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.ДатаНачала Get start)

                //  *** End programmer edit section *** (Тариф.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                //  *** Start programmer edit section *** (Тариф.ДатаНачала Get end)

                //  *** End programmer edit section *** (Тариф.ДатаНачала Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.ДатаНачала Set start)

                //  *** End programmer edit section *** (Тариф.ДатаНачала Set start)
                this.fДатаНачала = value;
                //  *** Start programmer edit section *** (Тариф.ДатаНачала Set end)

                //  *** End programmer edit section *** (Тариф.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.ДатаОкончания CustomAttributes)

        //  *** End programmer edit section *** (Тариф.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.ДатаОкончания Get start)

                //  *** End programmer edit section *** (Тариф.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                //  *** Start programmer edit section *** (Тариф.ДатаОкончания Get end)

                //  *** End programmer edit section *** (Тариф.ДатаОкончания Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.ДатаОкончания Set start)

                //  *** End programmer edit section *** (Тариф.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                //  *** Start programmer edit section *** (Тариф.ДатаОкончания Set end)

                //  *** End programmer edit section *** (Тариф.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Единица.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.Единица CustomAttributes)

        //  *** End programmer edit section *** (Тариф.Единица CustomAttributes)
        [StrLen(255)]
        public virtual string Единица
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.Единица Get start)

                //  *** End programmer edit section *** (Тариф.Единица Get start)
                string result = this.fЕдиница;
                //  *** Start programmer edit section *** (Тариф.Единица Get end)

                //  *** End programmer edit section *** (Тариф.Единица Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.Единица Set start)

                //  *** End programmer edit section *** (Тариф.Единица Set start)
                this.fЕдиница = value;
                //  *** Start programmer edit section *** (Тариф.Единица Set end)

                //  *** End programmer edit section *** (Тариф.Единица Set end)
            }
        }
        
        /// <summary>
        /// Формула.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.Формула CustomAttributes)

        //  *** End programmer edit section *** (Тариф.Формула CustomAttributes)
        [StrLen(255)]
        public virtual string Формула
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.Формула Get start)

                //  *** End programmer edit section *** (Тариф.Формула Get start)
                string result = this.fФормула;
                //  *** Start programmer edit section *** (Тариф.Формула Get end)

                //  *** End programmer edit section *** (Тариф.Формула Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.Формула Set start)

                //  *** End programmer edit section *** (Тариф.Формула Set start)
                this.fФормула = value;
                //  *** Start programmer edit section *** (Тариф.Формула Set end)

                //  *** End programmer edit section *** (Тариф.Формула Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.Стоимость CustomAttributes)

        //  *** End programmer edit section *** (Тариф.Стоимость CustomAttributes)
        [StrLen(255)]
        public virtual string Стоимость
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.Стоимость Get start)

                //  *** End programmer edit section *** (Тариф.Стоимость Get start)
                string result = this.fСтоимость;
                //  *** Start programmer edit section *** (Тариф.Стоимость Get end)

                //  *** End programmer edit section *** (Тариф.Стоимость Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.Стоимость Set start)

                //  *** End programmer edit section *** (Тариф.Стоимость Set start)
                this.fСтоимость = value;
                //  *** Start programmer edit section *** (Тариф.Стоимость Set end)

                //  *** End programmer edit section *** (Тариф.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Тариф.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.ВидУслуги CustomAttributes)

        //  *** End programmer edit section *** (Тариф.ВидУслуги CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.ВидУслуги ВидУслуги
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.ВидУслуги Get start)

                //  *** End programmer edit section *** (Тариф.ВидУслуги Get start)
                IIS.Umnyjj_dom.ВидУслуги result = this.fВидУслуги;
                //  *** Start programmer edit section *** (Тариф.ВидУслуги Get end)

                //  *** End programmer edit section *** (Тариф.ВидУслуги Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.ВидУслуги Set start)

                //  *** End programmer edit section *** (Тариф.ВидУслуги Set start)
                this.fВидУслуги = value;
                //  *** Start programmer edit section *** (Тариф.ВидУслуги Set end)

                //  *** End programmer edit section *** (Тариф.ВидУслуги Set end)
            }
        }
        
        /// <summary>
        /// Тариф.
        /// </summary>
        //  *** Start programmer edit section *** (Тариф.Поставщик CustomAttributes)

        //  *** End programmer edit section *** (Тариф.Поставщик CustomAttributes)
        [NotNull()]
        public virtual IIS.Umnyjj_dom.Поставщик Поставщик
        {
            get
            {
                //  *** Start programmer edit section *** (Тариф.Поставщик Get start)

                //  *** End programmer edit section *** (Тариф.Поставщик Get start)
                IIS.Umnyjj_dom.Поставщик result = this.fПоставщик;
                //  *** Start programmer edit section *** (Тариф.Поставщик Get end)

                //  *** End programmer edit section *** (Тариф.Поставщик Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Тариф.Поставщик Set start)

                //  *** End programmer edit section *** (Тариф.Поставщик Set start)
                this.fПоставщик = value;
                //  *** Start programmer edit section *** (Тариф.Поставщик Set end)

                //  *** End programmer edit section *** (Тариф.Поставщик Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТарифE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТарифE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТарифE", typeof(IIS.Umnyjj_dom.Тариф));
                }
            }
            
            /// <summary>
            /// "ТарифL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТарифL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТарифL", typeof(IIS.Umnyjj_dom.Тариф));
                }
            }
        }
    }
}
