//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Umnyjj_dom
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Управляющая компания.
    /// </summary>
    //  *** Start programmer edit section *** (УправляющаяКомпания CustomAttributes)

    //  *** End programmer edit section *** (УправляющаяКомпания CustomAttributes)
    [AutoAltered()]
    [Caption("Управляющая компания")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УправляющаяКомпанияE", new string[] {
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'"})]
    [View("УправляющаяКомпанияL", new string[] {
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'"})]
    public class УправляющаяКомпания : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fИНН;
        
        //  *** Start programmer edit section *** (УправляющаяКомпания CustomMembers)

        //  *** End programmer edit section *** (УправляющаяКомпания CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (УправляющаяКомпания.Наименование CustomAttributes)

        //  *** End programmer edit section *** (УправляющаяКомпания.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (УправляющаяКомпания.Наименование Get start)

                //  *** End programmer edit section *** (УправляющаяКомпания.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (УправляющаяКомпания.Наименование Get end)

                //  *** End programmer edit section *** (УправляющаяКомпания.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (УправляющаяКомпания.Наименование Set start)

                //  *** End programmer edit section *** (УправляющаяКомпания.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (УправляющаяКомпания.Наименование Set end)

                //  *** End programmer edit section *** (УправляющаяКомпания.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        //  *** Start programmer edit section *** (УправляющаяКомпания.ИНН CustomAttributes)

        //  *** End programmer edit section *** (УправляющаяКомпания.ИНН CustomAttributes)
        [StrLen(255)]
        public virtual string ИНН
        {
            get
            {
                //  *** Start programmer edit section *** (УправляющаяКомпания.ИНН Get start)

                //  *** End programmer edit section *** (УправляющаяКомпания.ИНН Get start)
                string result = this.fИНН;
                //  *** Start programmer edit section *** (УправляющаяКомпания.ИНН Get end)

                //  *** End programmer edit section *** (УправляющаяКомпания.ИНН Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (УправляющаяКомпания.ИНН Set start)

                //  *** End programmer edit section *** (УправляющаяКомпания.ИНН Set start)
                this.fИНН = value;
                //  *** Start programmer edit section *** (УправляющаяКомпания.ИНН Set end)

                //  *** End programmer edit section *** (УправляющаяКомпания.ИНН Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УправляющаяКомпанияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УправляющаяКомпанияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УправляющаяКомпанияE", typeof(IIS.Umnyjj_dom.УправляющаяКомпания));
                }
            }
            
            /// <summary>
            /// "УправляющаяКомпанияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УправляющаяКомпанияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УправляющаяКомпанияL", typeof(IIS.Umnyjj_dom.УправляющаяКомпания));
                }
            }
        }
    }
}
